---
title: "proj5"
author: "Ying"
date: "12/3/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
```

```{r}
setwd("~/Desktop/Fall2016-proj5-proj5-grp10-master/doc")
source('../lib/simplify_breeds.R')
```

```{r message=F, echo=F}

load("~/Desktop/shelter_data_new.RData")
data<-shelter_data_new



### Days in shelter 
# 
# trans.time<-function(variable){
#   
#   haha<- strsplit(variable," ")
#   hehe<-vector()
#   
#   n<-
# 
# for (i in 1:n){
#   if (haha[[i]][2]=="year"){
#     hehe[i]<-haha[[i]][1]
#   }else if (haha[[i]][2]=="years"){
#     hehe[i]<-haha[[i]][1]
#   }else if (haha[[i]][2]=="month"){
#     hehe[i]<-as.numeric(haha[[i]][1])/12
#   }else if (haha[[i]][2]=="months"){
#     hehe[i]<-as.numeric(haha[[i]][1])/12
#   }else if (haha[[i]][2]=="weeks"){
#     hehe[i]<-as.numeric(haha[[i]][1])/48
#   }
#   # else if (haha[[i]][2]=="week"){
#   #   hehe[i]<-as.numeric(haha[[i]][1])/48
#   # }else if (haha[[i]][2]=="days"){
#   #   hehe[i]<-as.numeric(haha[[i]][1])/365
#   # }
#   else{
#     hehe[i]<-0
#   }
# }
#   hehe<-as.numeric(hehe)
#   return(hehe)
# }
# 
# age_upon_intake<-trans.time(data$`Age upon Intake`)
# age_upon_outcome<-trans.time(data$`Age upon Outcome`)

# Time difference 
days_in_shelter<-as.Date(data$`Outcome Date`,"%y-%m-%d")-as.Date(data$`Intake Date`,"%y-%m-%d")

# Check and correct for error in days.
days_in_shelter[which(days_in_shelter<0)]=
  abs(days_in_shelter[which(days_in_shelter<0)])

# Plot the days in shelter according to the intake type.
p1<-plot_ly(data,x=~`Intake Condition`,y=~days_in_shelter,type = 'box',
        color = ~`Intake Condition`)
p1
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Animal numbers in shelter days to days (overall)

animal.num<-function(dataset){
  
  record_time<-seq(as.Date("2013-10-01"),as.Date("2015-09-30"),by="day")
  n<-length(record_time)
  
  take_in_num<-vector()
  for (i in 1:n){
  take_in_num[i]<-length(which(dataset$`Intake Date`<= record_time[i]))
  }

  take_out_num<-vector()
  for (i in 1:n){
  take_out_num[i]<-length(which(dataset$`Outcome Date`<= record_time[i]))
  }
  
  animal_in_shelter<-take_in_num-take_out_num

  return(data.frame(record_time,animal_in_shelter))
  
}

all_type_animal_num<-animal.num(data)
names(all_type_animal_num)

p2<-plot_ly(x=~record_time,y=~animal_in_shelter,data =all_type_animal_num ,type = 'scatter', mode = 'lines')%>%
  layout(title = "Animal Numbers in Shelter over time",
         xaxis = list(title = "", tickangle = 45, position=.15, domain=c(0,.9)),
         yaxis = list(title = " ", domain=c(.13,1)))
p2
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Animal numbers in shelter days to days (Group by cats and dogs)
names(data)
# unique(data$`Animal Type`) 
# "Dog"       "Cat"       "Livestock" "Other"     "Bird" 

animal.type.num<-function(dataset){
  
  dog_data<-dataset[which(dataset$`Animal Type`=="Dog"),]
  cat_data<-dataset[which(dataset$`Animal Type`=="Cat"),]
  livestock_data<-dataset[which(dataset$`Animal Type`=="Livestock"),]
  other_data<-dataset[which(dataset$`Animal Type`=="Other"),]
  bird_data<-dataset[which(dataset$`Animal Type`=="Bird"),]

  
  dog_num<-animal.num(dog_data)
  cat_num<-animal.num(cat_data)
  livestock_num<-animal.num(livestock_data)
  other_num<-animal.num(other_data)
  bird_num<-animal.num(bird_data)
  
  
  hehe<-data.frame(dog_num,cat_num[,2],livestock_num[,2],other_num[,2],bird_num[,2])
  colnames(hehe)<-c("Record Time",unique(data$`Animal Type`))
  
  return(hehe)
}

group_animal_num<-animal.type.num(data)

# plot

xaxis <- list(title = "",
             showgrid = FALSE)

yaxis <- list(title = "",
             showgrid = FALSE,
             zeroline = FALSE,
             showline = FALSE)

p3<-plot_ly(group_animal_num, x=~`Record Time`, y=~Dog,
        type = 'scatter', mode = 'lines',name='dogs',
        line = list(color = 'rgb(249, 154, 137)', width = 2))%>%
  add_trace(y=~Cat,type = 'scatter', mode = 'lines',name='cats',
        line =  list(color = 'rgb(137, 163, 249)', width = 2))%>%
  add_trace(y=~Livestock,type='scatter', mode = 'lines',name='livestock',
        line =  list(color = 'rgb(68, 181, 80)', width = 2))%>%
  add_trace(y=~Other,type='scatter', mode = 'lines',name='other',
        line =  list(color = 'rgb(143, 68, 181)', width = 2))%>%
  add_trace(y=~Bird,type='scatter', mode = 'lines',name='birds',
        line =  list(color = 'rrgb(244, 220, 66)', width = 2))%>%
   layout(title = "Numbers of group in shelter over time", 
          xaxis = xaxis,
          yaxis = yaxis) 

p3 
## Interesting founding: cat numbers in shelter has a seasonal change.
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
names(data)
#Numbers in shelter may lead by the Sex upon Intake


sex.type.num<-function(dataset){
  
  nm_data<-dataset[which(dataset$`Sex upon Intake`=="Neutered Male"),]
  sf_data<-dataset[which(dataset$`Sex upon Intake`=="Spayed Female"),]
  if_data<-dataset[which(dataset$`Sex upon Intake`=="Intact Female"),]
  im_data<-dataset[which(dataset$`Sex upon Intake`=="Intact Male"),]
  uk_data<-dataset[which(dataset$`Sex upon Intake`=="Unknown"),]
  
  nm_num<-animal.num(nm_data)
  sf_num<-animal.num(sf_data)
  if_num<-animal.num(if_data)
  im_num<-animal.num(im_data)
  uk_num<-animal.num(uk_data)
  
  
  hehe<-data.frame(nm_num,sf_num[,2],if_num[,2],im_num[,2],uk_num[,2])
  colnames(hehe)<-c("Record Time",unique(data$`Sex upon Intake`)[1:5])
  
  return(hehe)
}
 
sex_type_num<-sex.type.num(data)
names(sex_type_num)

##Plot 

yaxis <- list(title = "",
             showgrid = FALSE)

yaxis <- list(title = "",
             showgrid = FALSE,
             zeroline = FALSE,
             showline = FALSE)

p4<-plot_ly(sex_type_num, x=~`Record Time`, y=~`Neutered Male`,
        type = 'scatter', mode = 'lines',name='Neutered Male',
        line = list(color = 'rgb(249, 154, 137)', width = 2))%>%
  
  add_trace(y=~`Spayed Female`,
            type = 'scatter', mode = 'lines',name='Spayed Female',
            line =  list(color = 'rgb(137, 163, 249)', width = 2))%>%
  
  add_trace(y=~`Intact Female`,
            type='scatter', mode = 'lines',name='Intact Female',
            line =  list(color = 'rgb(68, 181, 80)', width = 2))%>%
  
  add_trace(y=~`Intact Male`,
            type='scatter', mode = 'lines',name='Intact Male',
            line =  list(color = 'rgb(143, 68, 181)', width = 2))%>%
  
  add_trace(y=~Unknown,type='scatter', mode = 'lines',name='Unknown',
        line =  list(color = 'rgb(244, 220, 66)', width = 2))%>%
  
   layout(title = "Numbers of group by sex in shelter over time", 
          xaxis = xaxis,
          yaxis = yaxis) 
p4
# Interesting founding:
# Intact female or male has a seasonal change 


```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Combining with the founding in above, I take a look at the dog and cat grouped by the sex.

# dogs data 
dog_data<-data[which(data$`Animal Type`=="Dog"),]
dog_sex_type_num<-sex.type.num(dog_data)
p5<-plot_ly(dog_sex_type_num, x=~`Record Time`, y=~`Neutered Male`,
        type = 'scatter', mode = 'lines',name='Neutered Male',
        line = list(color = 'rgb(249, 154, 137)', width = 2))%>%
  
  add_trace(y=~`Spayed Female`,
            type = 'scatter', mode = 'lines',name='Spayed Female',
            line =  list(color = 'rgb(137, 163, 249)', width = 2))%>%
  
  add_trace(y=~`Intact Female`,
            type='scatter', mode = 'lines',name='Intact Female',
            line =  list(color = 'rgb(68, 181, 80)', width = 2))%>%
  
  add_trace(y=~`Intact Male`,
            type='scatter', mode = 'lines',name='Intact Male',
            line =  list(color = 'rgb(143, 68, 181)', width = 2))%>%
  
  add_trace(y=~Unknown,type='scatter', mode = 'lines',name='Unknown',
        line =  list(color = 'rgb(244, 220, 66)', width = 2))%>%
  
   layout(title = "Numbers of dogs group by sex in shelter over time", 
          xaxis = xaxis,
          yaxis = yaxis) 

p5

# cats data

cat_data<-data[which(data$`Animal Type`=="Cat"),]
cat_sex_type_num<-sex.type.num(cat_data)

p6<-plot_ly(cat_sex_type_num, x=~`Record Time`, y=~`Neutered Male`,
        type = 'scatter', mode = 'lines',name='Neutered Male',
        line = list(color = 'rgb(249, 154, 137)', width = 2))%>%
  
  add_trace(y=~`Spayed Female`,
            type = 'scatter', mode = 'lines',name='Spayed Female',
            line =  list(color = 'rgb(137, 163, 249)', width = 2))%>%
  
  add_trace(y=~`Intact Female`,
            type='scatter', mode = 'lines',name='Intact Female',
            line =  list(color = 'rgb(68, 181, 80)', width = 2))%>%
  
  add_trace(y=~`Intact Male`,
            type='scatter', mode = 'lines',name='Intact Male',
            line =  list(color = 'rgb(143, 68, 181)', width = 2))%>%
  
  add_trace(y=~Unknown,type='scatter', mode = 'lines',name='Unknown',
        line =  list(color = 'rgb(244, 220, 66)', width = 2))%>%
  
   layout(title = "Numbers of cats group by sex in shelter over time", 
          xaxis = xaxis,
          yaxis = yaxis) 

p6
#No matter what kind of problems that cats have, summer cats numbers  in shelter in summer are significant higher than other months especially for those who are able to have children

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
#From this on, we focus on dogs
#Outcome vs sex 


#Deal with the data

percent.out.sex<-function(dataset){
  out_sex<-matrix(nrow = 7 ,ncol = 5)
  colnames(out_sex)<-c("Neutered Male","Spayed Female","Intact Female","Intact Male","Unknown")
  rownames(out_sex)<-c("Return to Owner","Transfer",
                     "Adoption","Euthanasia","Died","Missing","Disposal")

 for (i in 1:7){
   for (j in 1:5){
     out_sex[i,j]<-length(which(dataset$`Sex upon Intake`==colnames(out_sex)[j]&
                                 dataset$`Outcome Type`==rownames(out_sex)[i]))/
       length(which(dataset$`Outcome Type`==rownames(out_sex)[i]))
   }
 }
  
  out_sex<-data.frame(round(out_sex*100,1))
  
  return(out_sex)
}


out_sex<-percent.out.sex(dog_data)


#Plot

top_labels <- colnames(out_sex)

p7 <- plot_ly(out_sex, x = ~Neutered.Male, y = rownames(out_sex), type = 'bar', orientation = 'h',
             marker = list(color = 'rgba(38, 24, 74, 0.8)',
                           line = list(color = 'rgb(248, 248, 249)', width = 1)),
             name='Neutered<br>Male') %>%
  add_trace(x = ~Spayed.Female, marker = list(color = 'rgba(71, 58, 131, 0.8)'),
            name='Spayed<br>Female') %>%
  add_trace(x = ~Intact.Female, marker = list(color = 'rgba(122, 120, 168, 0.8)'),
            name='Intact<br>Female') %>%
  add_trace(x = ~Intact.Male, marker = list(color = 'rgba(164, 163, 204, 0.85)'),
            name='Intact<br>Male') %>%
  add_trace(x = ~Unknown, marker = list(color = 'rgba(190, 192, 213, 1)'),
            name='Unkown') %>%
  layout(xaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE,
                      domain = c(0.15, 1)),
         yaxis = list(title = "",
                      showgrid = FALSE,
                      showline = FALSE,
                      showticklabels = FALSE,
                      zeroline = FALSE),
         title = "Outcome types v.s. Sex Type upon Intake",
         barmode = 'stack',
         paper_bgcolor = 'rgb(248, 248, 255)', plot_bgcolor = 'rgb(248, 248, 255)',
         margin = list(l = 120, r = 10, t = 140, b = 80)
         ) %>%
  # labeling the y-axis
  add_annotations(xref = 'paper', yref = 'y', x = 0.14, y = rownames(out_sex),
                  xanchor = 'right',
                  text = rownames(out_sex),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                  showarrow = FALSE, align = 'right') %>%
  # labeling the percentages of each bar (x_axis)
  add_annotations(xref = 'x', yref = 'y',
                  x = ~Neutered.Male/2, y = rownames(out_sex),
                  text = paste(out_sex[,"Neutered.Male"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~Neutered.Male+Spayed.Female/2, y = rownames(out_sex),
                  text = paste(out_sex[,"Spayed.Female"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~Neutered.Male+Spayed.Female+Intact.Female/2, y = rownames(out_sex),
                  text = paste(out_sex[,"Intact.Female"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~Neutered.Male+Spayed.Female+Intact.Female+Intact.Male/2, 
                  y = rownames(out_sex),
                  text = paste(out_sex[,"Intact.Male"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) %>%
  add_annotations(xref = 'x', yref = 'y',
                  x = ~Neutered.Male+Spayed.Female+Intact.Female+Intact.Male+Unknown/2,
                  y = rownames(out_sex),
                  text = paste(out_sex[,"Unknown"], '%'),
                  font = list(family = 'Arial', size = 12,
                              color = 'rgb(248, 248, 255)'),
                  showarrow = FALSE) 

p7

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Dogs names vs outcome
# deal with the data

percent.out.name<-function(dataset){
  
  out_name<-matrix(nrow = 7 ,ncol = 2)
  colnames(out_name)<-c("Have Name","No Name")
  rownames(out_name)<-c("Return to Owner","Transfer",
                     "Adoption","Euthanasia","Died","Missing","Disposal")

 for (i in 1:7){
     out_name[i,1]<-length(which(dataset$Name!=""&
                                 dataset$`Outcome Type`==rownames(out_sex)[i]))/
       length(which(dataset$Name!=""))
     
     out_name[i,2]<-length(which(dataset$Name == "" &
                                 dataset$`Outcome Type`==rownames(out_sex)[i]))/
       length(which(dataset$Name==""))
 }
  
  return(data.frame(round(out_name*100,1)))
}

out_name<-percent.out.name(dog_data)



p_1 <- plot_ly(out_name, x = ~Have.Name, y = ~reorder(rownames(out_name), Have.Name),
              name = 'Outcome vs dogs who have a name',
              type = 'bar', orientation = 'h',
              marker = list(color = 'rgba(50, 171, 96, 0.6)',
                            line = list(color = 'rgba(50, 171, 96, 1.0)', width = 1))) %>%
  layout(yaxis = list(title = "",showgrid = FALSE, showline = FALSE, showticklabels = TRUE, domain= c(0, 0.85)),
         xaxis = list(zeroline = FALSE, showline = FALSE, showticklabels = TRUE, showgrid = TRUE)) %>%
  add_annotations(xref = 'x1', yref = 'y',
                  x = ~Have.Name + 6,  y =rownames(out_name),
                  text = paste( round(out_name$Have.Name, 1) , '%'),
                  font = list(family = 'Arial', size = 12, color = 'rgb(50, 171, 96)'),
                  showarrow = FALSE)

p_2<-plot_ly(out_name, x = ~No.Name, y = ~reorder(rownames(out_name), Have.Name),
              name = 'Outcome vs dogs who have no name',
              type = 'bar', orientation = 'h',
              marker = list(color = 'rgba(245, 182, 140,0.6)',
                            line = list(color = 'rgba(245, 182, 140,0.6)', width = 1))) %>%
  layout(yaxis = list(showgrid = FALSE, showline = TRUE, showticklabels = FALSE,domain= c(0, 0.85)),
         xaxis = list(zeroline = FALSE, showline = FALSE, showticklabels = TRUE, showgrid = TRUE,side = 'top'))
# %>%
#   add_annotations(xref = 'x1', yref = 'y',
#                   x = ~No.Name+6,  y =rownames(out_name),
#                   text = paste( round(out_name$No.Name, 1) , '%'),
#                   font = list(family = 'Arial', size = 12, color = 'rgb(245, 182, 140)'),
#                   showarrow = FALSE)


subplot(p_1, p_2) %>%
  layout(title = 'Dogs have & no name for seven outcomes',
         legend = list(x = 0.029, y = 1.038,
                       font = list(size = 10)),
         margin = list(l = 100, r = 20, t = 70, b = 70),
         paper_bgcolor = 'rgb(248, 248, 255)',
         plot_bgcolor = 'rgb(248, 248, 255)') 


```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Outcome vs days in shelter.


dog_days_in_shelter<-as.Date(dog_data$`Outcome Date`,"%y-%m-%d")-as.Date(dog_data$`Intake Date`,"%y-%m-%d")

dog_days_in_shelter[which(dog_days_in_shelter<0)]=
  abs(dog_days_in_shelter[which(dog_days_in_shelter<0)])

out_days<-data.frame(dog_days_in_shelter,dog_data$`Outcome Type`)[which(
  dog_data$`Outcome Type`=="Return to Owner"|
    dog_data$`Outcome Type`=="Transfer"|
    dog_data$`Outcome Type`=="Adoption"|
    dog_data$`Outcome Type`=="Euthanasia"
  ),]

out_days[,2]<-as.factor(as.character(out_days[,2]))

colnames(out_days)<-c("Days","Outcome.Type")
out_days<-data.frame(as.numeric(out_days[,1]),out_days[,2])

p8<-plot_ly(out_days, y = ~Days, x = ~Outcome.Type,
            color = ~Outcome.Type, 
            type = 'box')%>%
  layout(title='Days in shelter vs Outcome type')

```

```{r}
#Sankey network

#Create the data
library(networkD3)
sankey.data<-function(dataset){
  
  sdata<-dataset[which(
  dataset$`Outcome Type`=="Return to Owner"|
    dataset$`Outcome Type`=="Transfer"|
    dataset$`Outcome Type`=="Adoption"|
    dataset$`Outcome Type`=="Euthanasia"),]
  
  
  dog_nodes<-c(unique(dataset$`Intake Type`),unique(dataset$`Intake Condition`),
             "Return to Owner","Transfer","Adoption","Euthanasia" )
  dog_link<-matrix(nrow = 64, ncol = 3 )
  dog_link[,1]<-c(rep(0,8),rep(1,8),rep(2,8),rep(3,8),
                rep(4,4),rep(5,4),rep(6,4),rep(7,4),
                rep(8,4),rep(9,4),rep(10,4),rep(11,4))
  dog_link[,2]<-c(rep(4:11,4),rep(12:15,8))
  
  
  for (i in 1:64){
    if(i<=32){
      dog_link[i,3]<-length(which(sdata$`Intake Type`==dog_nodes[dog_link[i,1]+1] & 
               sdata$`Intake Condition`== dog_nodes[dog_link[i,2]+1]))
      }else{
        dog_link[i,3]<-length(which(sdata$`Intake Condition`==dog_nodes[dog_link[i,1]+1] &
                                      sdata$`Outcome Type`== dog_nodes[dog_link[i,2]+1]))
      }
  }
  
  
  
  colnames(dog_link)<-c("source","target","value")
  
  haha<-list()
  haha$nodes<-as.data.frame(dog_nodes)
  haha$links<-as.data.frame(dog_link)
  
  return(haha)
  
}


kk<-sankey.data(dog_data)
p10<-sankeyNetwork(Links = kk$links, Nodes = kk$nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "dog_nodes",
              units = "", fontSize = 12, nodeWidth = 40,nodePadding = 8,
              margin = NULL, height = 400, width = 800,
              colourScale = JS("d3.scale.category20()"))
p10

```

